spring:
  datasource:
    url: jdbc:mysql://jpasampleshop.cfgwexy8deov.ap-northeast-2.rds.amazonaws.com:3306/jpasampleshop?useSSL=false
    username: jpasampleshop
    password: jpasampleshop
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace